import mongoose from 'mongoose';
import dotenv from 'dotenv';
import path from 'path';
import { fileURLToPath } from 'url';
import Product from '../models/Product.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

dotenv.config({ path: path.join(__dirname, '../../.env') });
dotenv.config({ path: path.join(__dirname, '../../../.env') });

const MONGODB_URI = process.env.MONGODB_URI || 'mongodb://localhost:27017/shopsphere';

const SEED_PRODUCTS = [
  // --- GAMING ---
  {
    name: 'Wireless Ergonomic Gaming Mouse',
    slug: 'wireless-gaming-mouse',
    description: 'Ultra-lightweight wireless gaming mouse with 26K DPI optical sensor, custom RGB lighting, and 80-hour battery life for competitive gaming.',
    brand: 'ApexGear',
    category: 'Gaming',
    subcategory: 'Peripherals',
    price: 1499,
    compareAtPrice: 1999,
    stock: 42,
    sku: 'GM-001',
    images: [
      { url: 'https://images.unsplash.com/photo-1615663245857-ac93bb7c39e7?w=800&auto=format&fit=crop&q=80', alt: 'Wireless Gaming Mouse Front' },
      { url: 'https://images.unsplash.com/photo-1527864550417-7fd91fc51a46?w=800&auto=format&fit=crop&q=80', alt: 'Wireless Gaming Mouse Side' },
    ],
    rating: 4.7,
    reviewCount: 2431,
    tags: ['gaming', 'wireless', 'mouse', 'rgb', 'pc'],
    isFeatured: true,
    isActive: true,
  },
  {
    name: 'Mechanical RGB Keyboard (Hot-swappable)',
    slug: 'mechanical-rgb-keyboard',
    description: 'Hot-swappable 75% mechanical keyboard with factory-lubed linear switches, sound-absorbing foam, and customizable keymaps.',
    brand: 'KeyMaster',
    category: 'Gaming',
    subcategory: 'Keyboards',
    price: 3299,
    compareAtPrice: 4299,
    stock: 28,
    sku: 'GM-002',
    images: [
      { url: 'https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80', alt: 'RGB Mechanical Keyboard' },
    ],
    rating: 4.8,
    reviewCount: 1250,
    tags: ['gaming', 'keyboard', 'mechanical', 'rgb'],
    isFeatured: true,
    isActive: true,
  },
  {
    name: '7.1 Surround Sound Gaming Headset',
    slug: 'surround-sound-gaming-headset',
    description: 'Immersive 7.1 virtual surround sound gaming headset with detachable noise-canceling microphone and breathable memory foam earcups.',
    brand: 'AcousticPalace',
    category: 'Gaming',
    subcategory: 'Audio',
    price: 2499,
    compareAtPrice: 3499,
    stock: 35,
    sku: 'GM-003',
    images: [
      { url: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80', alt: '7.1 Gaming Headset' },
    ],
    rating: 4.6,
    reviewCount: 890,
    tags: ['gaming', 'headset', 'audio', '7.1'],
    isFeatured: false,
    isActive: true,
  },
  {
    name: 'Curved QHD 165Hz Gaming Monitor 27-inch',
    slug: 'curved-qhd-165hz-gaming-monitor',
    description: '27-inch 1440p QHD curved gaming monitor with 165Hz refresh rate, 1ms response time, and HDR400 for liquid-smooth gameplay.',
    brand: 'VisionPro',
    category: 'Gaming',
    subcategory: 'Monitors',
    price: 18999,
    compareAtPrice: 24999,
    stock: 12,
    sku: 'GM-004',
    images: [
      { url: 'https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80', alt: 'Curved Gaming Monitor' },
    ],
    rating: 4.9,
    reviewCount: 540,
    tags: ['gaming', 'monitor', 'qhd', '165hz'],
    isFeatured: true,
    isActive: true,
  },

  // --- ELECTRONICS ---
  {
    name: 'Pro ANC Wireless Headphones with Spatial Audio',
    slug: 'pro-anc-wireless-headphones',
    description: 'Flagship wireless headphones featuring hybrid active noise cancellation, 40-hour battery life, and high-fidelity spatial audio drivers.',
    brand: 'AcousticPalace',
    category: 'Electronics',
    subcategory: 'Audio',
    price: 4999,
    compareAtPrice: 6999,
    stock: 50,
    sku: 'EL-001',
    images: [
      { url: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80', alt: 'ANC Wireless Headphones' },
    ],
    rating: 4.8,
    reviewCount: 3120,
    tags: ['audio', 'headphones', 'wireless', 'anc'],
    isFeatured: true,
    isActive: true,
  },
  {
    name: 'True Wireless Earbuds with Wireless Charging',
    slug: 'true-wireless-earbuds-charging',
    description: 'Compact TWS earbuds featuring crystal-clear voice mics, IPX7 water resistance, and wireless charging case delivering 32h playback.',
    brand: 'SoundPulse',
    category: 'Electronics',
    subcategory: 'Audio',
    price: 1999,
    compareAtPrice: 2999,
    stock: 65,
    sku: 'EL-002',
    images: [
      { url: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80', alt: 'TWS Earbuds' },
    ],
    rating: 4.5,
    reviewCount: 1420,
    tags: ['audio', 'earbuds', 'wireless', 'tws'],
    isFeatured: false,
    isActive: true,
  },
  {
    name: 'Smart Fitness Tracker with AMOLED Display',
    slug: 'smart-fitness-tracker-amoled',
    description: 'Sleek smart band with 1.4-inch vibrant AMOLED display, continuous heart rate monitoring, SpO2 sensor, and 14-day battery life.',
    brand: 'FitPulse',
    category: 'Electronics',
    subcategory: 'Wearables',
    price: 2299,
    compareAtPrice: 3199,
    stock: 40,
    sku: 'EL-003',
    images: [
      { url: 'https://images.unsplash.com/photo-1510017803434-a899398421b3?w=800&auto=format&fit=crop&q=80', alt: 'Smart Fitness Tracker' },
    ],
    rating: 4.6,
    reviewCount: 980,
    tags: ['wearables', 'smartwatch', 'fitness', 'amoled'],
    isFeatured: true,
    isActive: true,
  },
  {
    name: 'Portable Waterproof Bluetooth Speaker 20W',
    slug: 'portable-waterproof-bluetooth-speaker',
    description: 'Rugged 20W outdoor Bluetooth speaker with deep punchy bass, IP67 dust/water resistance, and 16-hour playtime.',
    brand: 'SoundPulse',
    category: 'Electronics',
    subcategory: 'Audio',
    price: 1799,
    compareAtPrice: 2499,
    stock: 30,
    sku: 'EL-004',
    images: [
      { url: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&auto=format&fit=crop&q=80', alt: 'Bluetooth Speaker' },
    ],
    rating: 4.7,
    reviewCount: 760,
    tags: ['audio', 'speaker', 'bluetooth', 'waterproof'],
    isFeatured: false,
    isActive: true,
  },

  // --- FASHION ---
  {
    name: 'Palamner Royal Kanchipuram Handloom Silk Saree',
    slug: 'palamner-royal-kanchipuram-silk-saree',
    description: 'Exquisite handloom silk saree with authentic gold zari weave, peacock motif borders, and unstitched blouse piece crafted in Palamner.',
    brand: 'Palamner Silks',
    category: 'Fashion',
    subcategory: 'Ethnic Wear',
    price: 4999,
    compareAtPrice: 7499,
    stock: 15,
    sku: 'FA-001',
    images: [
      { url: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=800&auto=format&fit=crop&q=80', alt: 'Palamner Silk Saree Front' },
    ],
    rating: 4.9,
    reviewCount: 680,
    tags: ['fashion', 'saree', 'silk', 'ethnic', 'palamner'],
    isFeatured: true,
    isActive: true,
  },
  {
    name: 'Men\'s Tailored Slim Fit Linen Blazer',
    slug: 'mens-tailored-slim-fit-linen-blazer',
    description: 'Lightweight premium linen blazer with structured shoulders, notch lapel, and versatile design for smart-casual and formal occasions.',
    brand: 'UrbanCraft',
    category: 'Fashion',
    subcategory: 'Men\'s Apparel',
    price: 2799,
    compareAtPrice: 3999,
    stock: 22,
    sku: 'FA-002',
    images: [
      { url: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=800&auto=format&fit=crop&q=80', alt: 'Linen Blazer' },
    ],
    rating: 4.6,
    reviewCount: 410,
    tags: ['fashion', 'men', 'blazer', 'linen', 'formal'],
    isFeatured: false,
    isActive: true,
  },
  {
    name: 'Handcrafted Genuine Leather Crossbody Tote',
    slug: 'handcrafted-genuine-leather-crossbody-tote',
    description: 'Full-grain artisan leather tote bag featuring handcrafted stitching, spacious organizer pockets, and detachable shoulder strap.',
    brand: 'Heritage Leathers',
    category: 'Fashion',
    subcategory: 'Bags & Accessories',
    price: 3499,
    compareAtPrice: 4999,
    stock: 18,
    sku: 'FA-003',
    images: [
      { url: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&auto=format&fit=crop&q=80', alt: 'Leather Crossbody Tote' },
    ],
    rating: 4.8,
    reviewCount: 520,
    tags: ['fashion', 'bag', 'leather', 'tote'],
    isFeatured: true,
    isActive: true,
  },
  {
    name: 'Classic Vintage Chronograph Stainless Steel Watch',
    slug: 'classic-vintage-chronograph-watch',
    description: 'Timeless chronograph watch featuring Japanese quartz movement, scratch-resistant sapphire crystal glass, and 50m water resistance.',
    brand: 'Crown watches',
    category: 'Fashion',
    subcategory: 'Watches',
    price: 3999,
    compareAtPrice: 5999,
    stock: 25,
    sku: 'FA-004',
    images: [
      { url: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=800&auto=format&fit=crop&q=80', alt: 'Chronograph Watch' },
    ],
    rating: 4.7,
    reviewCount: 390,
    tags: ['fashion', 'watch', 'chronograph', 'accessories'],
    isFeatured: false,
    isActive: true,
  },

  // --- BEAUTY ---
  {
    name: 'Ayurvedic Kumkumadi Radiance Face Serum 30ml',
    slug: 'ayurvedic-kumkumadi-radiance-face-serum',
    description: 'Pure 100% natural Ayurvedic night serum blended with Kashmir saffron, lotus extracts, and 24K gold foil for ageless illumination.',
    brand: 'Palace Botanicals',
    category: 'Beauty',
    subcategory: 'Skincare',
    price: 799,
    compareAtPrice: 1199,
    stock: 60,
    sku: 'BE-001',
    images: [
      { url: 'https://images.unsplash.com/photo-1608248597261-5421778b1621?w=800&auto=format&fit=crop&q=80', alt: 'Kumkumadi Serum' },
    ],
    rating: 4.9,
    reviewCount: 1850,
    tags: ['beauty', 'skincare', 'serum', 'ayurveda', 'glow'],
    isFeatured: true,
    isActive: true,
  },
  {
    name: 'Rose & Sandalwood Hydrating Facial Mist 100ml',
    slug: 'rose-sandalwood-hydrating-facial-mist',
    description: 'Refreshing facial mist distilled from organic Kannauj roses and pure Mysore sandalwood oil to hydrate and calm skin instantaneously.',
    brand: 'Palace Botanicals',
    category: 'Beauty',
    subcategory: 'Skincare',
    price: 499,
    compareAtPrice: 699,
    stock: 80,
    sku: 'BE-002',
    images: [
      { url: 'https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&auto=format&fit=crop&q=80', alt: 'Rose Facial Mist' },
    ],
    rating: 4.7,
    reviewCount: 640,
    tags: ['beauty', 'skincare', 'mist', 'rose', 'organic'],
    isFeatured: false,
    isActive: true,
  },
  {
    name: 'Matte Liquid Lipstick Set (4 Nude Shades)',
    slug: 'matte-liquid-lipstick-set-nude',
    description: 'Long-lasting, transfer-proof velvet matte liquid lipsticks enriched with Vitamin E and jojoba oil for comfortable all-day wear.',
    brand: 'LuxeGlow',
    category: 'Beauty',
    subcategory: 'Makeup',
    price: 899,
    compareAtPrice: 1299,
    stock: 45,
    sku: 'BE-003',
    images: [
      { url: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?w=800&auto=format&fit=crop&q=80', alt: 'Matte Liquid Lipstick Set' },
    ],
    rating: 4.6,
    reviewCount: 920,
    tags: ['beauty', 'makeup', 'lipstick', 'matte'],
    isFeatured: false,
    isActive: true,
  },
  {
    name: 'Organic Onion & Bhringraj Anti-Hairfall Oil 200ml',
    slug: 'organic-onion-bhringraj-hair-oil',
    description: 'Traditional cold-pressed hair oil with red onion extract, bhringraj, and almond oil to nourish scalp roots and boost shine.',
    brand: 'Palace Botanicals',
    category: 'Beauty',
    subcategory: 'Haircare',
    price: 399,
    compareAtPrice: 599,
    stock: 90,
    sku: 'BE-004',
    images: [
      { url: 'https://images.unsplash.com/photo-1608248540306-037000d0246a?w=800&auto=format&fit=crop&q=80', alt: 'Onion Hair Oil' },
    ],
    rating: 4.8,
    reviewCount: 1100,
    tags: ['beauty', 'haircare', 'hairoil', 'organic'],
    isFeatured: true,
    isActive: true,
  },

  // --- HOME ---
  {
    name: 'Brass Handcrafted Royal Peacock Diya Pair',
    slug: 'brass-handcrafted-royal-peacock-diya-pair',
    description: 'Solid heavy-grade brass peacock oil lamps with traditional antique finish, handcrafted by South Indian metal artisans.',
    brand: 'Heritage Crafts',
    category: 'Home',
    subcategory: 'Decor',
    price: 999,
    compareAtPrice: 1499,
    stock: 35,
    sku: 'HO-001',
    images: [
      { url: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?w=800&auto=format&fit=crop&q=80', alt: 'Brass Peacock Diya' },
    ],
    rating: 4.9,
    reviewCount: 380,
    tags: ['home', 'decor', 'brass', 'diya', 'artisan'],
    isFeatured: true,
    isActive: true,
  },
  {
    name: 'Ceramic Handcrafted Espresso Mug Set of 4',
    slug: 'ceramic-handcrafted-espresso-mug-set',
    description: 'Studio ceramic coffee mugs with reactive glaze finish, heat retention body, and ergonomic handles.',
    brand: 'EarthWare',
    category: 'Home',
    subcategory: 'Kitchen & Dining',
    price: 799,
    compareAtPrice: 1199,
    stock: 40,
    sku: 'HO-002',
    images: [
      { url: 'https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80', alt: 'Ceramic Espresso Mugs' },
    ],
    rating: 4.7,
    reviewCount: 290,
    tags: ['home', 'kitchen', 'ceramic', 'mugs', 'coffee'],
    isFeatured: false,
    isActive: true,
  },
  {
    name: 'Automatic Espresso & Cappuccino Coffee Machine 15-Bar',
    slug: 'automatic-espresso-cappuccino-coffee-machine',
    description: 'Professional 15-bar Italian pump espresso machine with steam wand milk frother, rapid thermo-block heater, and 1.5L removable water reservoir.',
    brand: 'BaristaPro',
    category: 'Home',
    subcategory: 'Kitchen Appliances',
    price: 8999,
    compareAtPrice: 12999,
    stock: 14,
    sku: 'HO-003',
    images: [
      { url: 'https://images.unsplash.com/photo-1517668808822-9ebe02f2a698?w=800&auto=format&fit=crop&q=80', alt: 'Espresso Coffee Machine' },
    ],
    rating: 4.8,
    reviewCount: 460,
    tags: ['home', 'appliances', 'coffee', 'espresso'],
    isFeatured: true,
    isActive: true,
  },
  {
    name: 'Handwoven Jute & Cotton Area Rug (4x6 ft)',
    slug: 'handwoven-jute-cotton-area-rug',
    description: 'Eco-friendly natural jute rug braided with soft cotton threads, perfect for living room accent flooring.',
    brand: 'EarthWare',
    category: 'Home',
    subcategory: 'Furnishings',
    price: 2499,
    compareAtPrice: 3499,
    stock: 20,
    sku: 'HO-004',
    images: [
      { url: 'https://images.unsplash.com/photo-1600121848594-d8644e57abab?w=800&auto=format&fit=crop&q=80', alt: 'Jute Area Rug' },
    ],
    rating: 4.6,
    reviewCount: 180,
    tags: ['home', 'furnishings', 'rug', 'jute', 'decor'],
    isFeatured: false,
    isActive: true,
  },

  // --- SPORTS ---
  {
    name: 'Carbon Fiber Pro Badminton Racket Set',
    slug: 'carbon-fiber-pro-badminton-racket-set',
    description: 'Dual high-tension carbon fiber badminton rackets with isometric head shape, 28-lbs string capacity, and padded carrying case.',
    brand: 'ApexSport',
    category: 'Sports',
    subcategory: 'Badminton',
    price: 1499,
    compareAtPrice: 2199,
    stock: 30,
    sku: 'SP-001',
    images: [
      { url: 'https://images.unsplash.com/photo-1626224583764-f87db24ac4ea?w=800&auto=format&fit=crop&q=80', alt: 'Badminton Racket Set' },
    ],
    rating: 4.7,
    reviewCount: 510,
    tags: ['sports', 'badminton', 'fitness', 'racket'],
    isFeatured: true,
    isActive: true,
  },
  {
    name: 'Non-Slip Eco-Friendly TPE Yoga Mat 6mm with Strap',
    slug: 'non-slip-tpe-yoga-mat-6mm',
    description: 'Dual-layer non-slip TPE yoga mat with alignment grid lines, 6mm cushioned protection, and moisture-resistant washable texture.',
    brand: 'ZenFit',
    category: 'Sports',
    subcategory: 'Fitness',
    price: 899,
    compareAtPrice: 1299,
    stock: 50,
    sku: 'SP-002',
    images: [
      { url: 'https://images.unsplash.com/photo-1601925260368-ae2f83cf8b7f?w=800&auto=format&fit=crop&q=80', alt: 'TPE Yoga Mat' },
    ],
    rating: 4.8,
    reviewCount: 870,
    tags: ['sports', 'yoga', 'fitness', 'mat'],
    isFeatured: false,
    isActive: true,
  },
  {
    name: 'Adjustable Dumbbell Set (10kg - Pair)',
    slug: 'adjustable-dumbbell-set-10kg-pair',
    description: 'Heavy-duty cast iron adjustable dumbbell set with anti-slip knurled handles and star lock collars for versatile home workouts.',
    brand: 'IronGrip',
    category: 'Sports',
    subcategory: 'Gym Equipment',
    price: 2499,
    compareAtPrice: 3499,
    stock: 25,
    sku: 'SP-003',
    images: [
      { url: 'https://images.unsplash.com/photo-1584735935682-2f2b69dff9d2?w=800&auto=format&fit=crop&q=80', alt: 'Adjustable Dumbbell Set' },
    ],
    rating: 4.9,
    reviewCount: 430,
    tags: ['sports', 'fitness', 'gym', 'dumbbells', 'workout'],
    isFeatured: true,
    isActive: true,
  },
  {
    name: 'Hydro-Insulated Stainless Steel Gym Water Bottle 1L',
    slug: 'hydro-insulated-stainless-steel-bottle-1l',
    description: 'Double-wall vacuum insulated stainless steel flask that keeps water ice-cold for 24 hours or hot for 12 hours with leakproof lid.',
    brand: 'ZenFit',
    category: 'Sports',
    subcategory: 'Accessories',
    price: 699,
    compareAtPrice: 999,
    stock: 75,
    sku: 'SP-004',
    images: [
      { url: 'https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&auto=format&fit=crop&q=80', alt: 'Insulated Gym Bottle' },
    ],
    rating: 4.6,
    reviewCount: 650,
    tags: ['sports', 'fitness', 'waterbottle', 'gym'],
    isFeatured: false,
    isActive: true,
  }
];

export async function seedProducts() {
  try {
    console.log('[Seed] Connecting to MongoDB...');
    await mongoose.connect(MONGODB_URI, { serverSelectionTimeoutMS: 5000 });
    console.log('[Seed] Connected to MongoDB.');

    // Clear existing products
    await Product.deleteMany({});
    console.log('[Seed] Cleared existing products from DB.');

    // Insert seed data
    const created = await Product.insertMany(SEED_PRODUCTS);
    console.log(`✅ [Seed] Successfully seeded ${created.length} products into MongoDB!`);

    await mongoose.disconnect();
    console.log('[Seed] MongoDB connection closed.');
    process.exit(0);
  } catch (error) {
    console.error('❌ [Seed] Error seeding products:', error);
    process.exit(1);
  }
}

if (process.argv[1] && process.argv[1].endsWith('products.js')) {
  seedProducts();
}

export default seedProducts;
