export const MOCK_PRODUCTS = [
  {
    id: 'prod-1',
    title: 'Palamner Traditional Silk Saree — Kanchipuram Gold Zari',
    brand: 'Palamner Silks',
    category: 'Fashion',
    categorySlug: 'fashion',
    price: 3499,
    originalPrice: 4999,
    discountPercentage: 30,
    rating: 4.8,
    reviewCount: 240,
    isNew: true,
    isBestseller: true,
    stock: 15,
    description: 'Authentic handwoven silk saree featuring exquisite gold zari work and rich royal crimson finish directly from Palamner artisan looms.',
    image: 'https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80',
    tags: ['saree', 'silk', 'traditional', 'wedding', 'palamner']
  },
  {
    id: 'prod-2',
    title: 'Wireless Active Noise Cancelling Headphones - Pro Audio',
    brand: 'AcousticPalace',
    category: 'Electronics',
    categorySlug: 'electronics',
    price: 2799,
    originalPrice: 3999,
    discountPercentage: 30,
    rating: 4.6,
    reviewCount: 184,
    isNew: false,
    isBestseller: true,
    stock: 28,
    description: 'Immersive sound with 40-hour battery life, fast charging, and premium memory foam ear cushions.',
    image: 'https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=600&auto=format&fit=crop&q=80',
    tags: ['headphones', 'wireless', 'audio', 'anc']
  },
  {
    id: 'prod-3',
    title: 'Brass Handcrafted Royal Peacock Diya Set (Pair of 2)',
    brand: 'Heritage Crafts',
    category: 'Home & Kitchen',
    categorySlug: 'home-kitchen',
    price: 899,
    originalPrice: 1299,
    discountPercentage: 31,
    rating: 4.9,
    reviewCount: 96,
    isNew: true,
    isBestseller: false,
    stock: 45,
    description: 'Solid brass peacock oil lamps with antique gold polish, ideal for home decor and festive rituals.',
    image: 'https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?w=600&auto=format&fit=crop&q=80',
    tags: ['decor', 'brass', 'diya', 'handicraft']
  },
  {
    id: 'prod-4',
    title: 'Ayurvedic Kumkumadi Glow Face Serum 30ml',
    brand: 'Palace Botanicals',
    category: 'Beauty & Care',
    categorySlug: 'beauty-care',
    price: 699,
    originalPrice: 999,
    discountPercentage: 30,
    rating: 4.7,
    reviewCount: 312,
    isNew: false,
    isBestseller: true,
    stock: 60,
    description: 'Formulated with 24K gold flakes, pure saffron, and sandalwood extracts for radiant youthfulness.',
    image: 'https://images.unsplash.com/photo-1608248597261-5421778b1621?w=600&auto=format&fit=crop&q=80',
    tags: ['skincare', 'ayurvedic', 'serum', 'glow']
  },
  {
    id: 'prod-5',
    title: 'Smart Fitness Tracker Watch with SpO2 & AMOLED Display',
    brand: 'Palace Pulse',
    category: 'Electronics',
    categorySlug: 'electronics',
    price: 1999,
    originalPrice: 2999,
    discountPercentage: 33,
    rating: 4.4,
    reviewCount: 142,
    isNew: true,
    isBestseller: false,
    stock: 22,
    description: 'Track heart rate, sleep, steps, and over 100 sports modes with 10 days battery endurance.',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&auto=format&fit=crop&q=80',
    tags: ['smartwatch', 'fitness', 'tech']
  },
  {
    id: 'prod-6',
    title: 'Artisanal Clay Water Handi with Lids (3 Liters)',
    brand: 'Chittoor Terracotta',
    category: 'Home & Kitchen',
    categorySlug: 'home-kitchen',
    price: 499,
    originalPrice: 799,
    discountPercentage: 38,
    rating: 4.8,
    reviewCount: 78,
    isNew: false,
    isBestseller: true,
    stock: 35,
    description: 'Natural alkaline clay pot that cools drinking water naturally while retaining trace minerals.',
    image: 'https://images.unsplash.com/photo-1578749556568-bc2c40e68b61?w=600&auto=format&fit=crop&q=80',
    tags: ['clay', 'kitchenware', 'earthen', 'handmade']
  },
  {
    id: 'prod-7',
    title: 'Men’s Hand-Embroidered Kurta Pyjama Set — Royal Navy',
    brand: 'Royal Couture',
    category: 'Fashion',
    categorySlug: 'fashion',
    price: 1899,
    originalPrice: 2499,
    discountPercentage: 24,
    rating: 4.5,
    reviewCount: 118,
    isNew: true,
    isBestseller: false,
    stock: 20,
    description: 'Soft cotton silk blend with Mandarin collar and subtle chikankari chest embroidery.',
    image: 'https://images.unsplash.com/photo-1597983073493-88cd35cf03b0?w=600&auto=format&fit=crop&q=80',
    tags: ['fashion', 'men', 'kurta', 'ethnic']
  },
  {
    id: 'prod-8',
    title: 'Organic Cardamom & Spices Gift Box (Chittoor Hills)',
    brand: 'Palace Harvest',
    category: 'Food & Pantry',
    categorySlug: 'food-pantry',
    price: 749,
    originalPrice: 999,
    discountPercentage: 25,
    rating: 4.9,
    reviewCount: 154,
    isNew: false,
    isBestseller: true,
    stock: 50,
    description: 'Freshly harvested green cardamom, cloves, and star anise sourced from single-origin plantations.',
    image: 'https://images.unsplash.com/photo-1596040033229-a9821ebd058d?w=600&auto=format&fit=crop&q=80',
    tags: ['spices', 'organic', 'gourmet', 'harvest']
  }
];
